spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 5
    validationQuery: SELECT 1 FROM DUAL
    initialSize: 5
    maxWait: 60000
    filters: stat,wall,log4j2
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.71.133:3306/bms?characterEncoding=utf8&useSSL=false
    maxPoolPreparedStatementPerConnectionSize: 20
    username: root
    password: toor
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
  thymeleaf:
    mode: HTML5
    cache: false
  devtools:
    restart:
      enabled: false
      exclude: classpath:templates/**
  velocity:
    enabled: false
mybatis:
  typeAliasesPackage: com.xj.**.entity
  mapper-locations: classpath*:mybatis/*Mapper.xml,com/xj/admin/bussiness/**/*Mapper.xml
logging:
  level:
    org:
      springframework:
        web: ERROR
    root: DEBUG
  config: classpath:log4j2.xml